stages:
  preprocessing:
    cmd: python preprocessing.py
    deps:
    - dataset/train.csv
    outs:
    - dataset/test_refactor.csv
    - dataset/train_refactor.csv
  trainModel:
    cmd: python train.py
    deps:
    - dataset/test_refactor.csv
    - dataset/train_refactor.csv
    metrics:
    - metrics.json:
        cache: false
