
name: your-workflow-name
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: Train model
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Install requirements
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          dvc run -n preprocessing -d dataset/train.csv -o dataset/test_refactor.csv -o dataset/train_refactor.csv -f python preprocessing.py
          dvc run -n trainModel -d dataset/test_refactor.csv -d dataset/train_refactor.csv -M metrics.json -f python train.py
          git fetch --prune
          # Report metrics
          echo "## Metrics" >> report.md
          dvc metrics diff --show-md main > report.md