
name: your-workflow-name
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: Train model
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Install requirements
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          dvc repro
          git fetch --prune
          # Report metrics
          echo "## Metrics" >> report.md
          dvc metrics diff --show-md main > report.md